version: '3.8'
services:
  frontend:
    build: ./frontend  
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173" 

  backend:
    build: ./BackEnd
    container_name: BackEnd
    restart: unless-stopped
    ports:
      - "3000:3000"


